name: dart_sm
description: Implementation of OSCCA SM2, SM3, and SM4 algorithms based on Dart language.
version: 0.1.5
homepage: https://github.com/luckykellan/dart_sm.git

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
